name: rerun-test

on:
  workflow_run:
    workflows: [test]
    types: [completed]

jobs:
  check-conclusion:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'konnichiwa'

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'