name: On Test Failure

on:
  repository_dispatch:
    types: [test_failure]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Notify about failure
      run: echo "Test workflow has failed!"
