name: Reaction to Test Failure

on:
  workflow_run:
    workflows: ["test"]
    types: 
      - completed

jobs:
  check_failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Notify Failure
        run: echo "The test workflow has failed!"
